name: spyder

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.14.3
  - numpy
  - pandas
  - scipy
  - matplotlib
  - spyder=6.1.*
  - pip
  - numba
  - pathlib
  - seaborn

  - pip:
    - curvefitgui
    - tk
  
