name: spyder

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - spyder=6.0.*
  - pip
  - numba
  - pathlib

  - mne # for neuroscience

  - pip:
    - curvefitgui
    - tk
  
