name: Image builder

on:
  schedule:
    - cron: '0 3 1-7 * SAT'
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  APP_IMAGE_NAME: spyder_container
  DB_IMAGE_NAME: spyder_container_neuroscience

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # Required for OIDC and Cosign

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for both images
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.APP_IMAGE_NAME }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.DB_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push both images with metadata
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          outputs: |
            type=image,name=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.APP_IMAGE_NAME }},push=true
            type=image,name=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.DB_IMAGE_NAME }},push=true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          no-cache: true


      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign both images with Cosign
        run: |
          # Sign the app image
          cosign sign --yes \
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.APP_IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest-app }}
          # Sign the db image
          cosign sign --yes \
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.DB_IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest-db }}
        env:
          COSIGN_EXPERIMENTAL: "true"
